import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { check } from "../hooks/lib/_edit-rules.mjs";

const ctx = { allowedModels: ["claude-opus-5-5", "claude-fable-5-1"] };
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dotclaude-edit-"));
const levels = (findings) => findings.map(([level]) => level);

test("removing an assertion from a test file asks", () => {
  const f = check(
    "Edit",
    {
      file_path: "/repo/tests/test_api.py",
      old_string: "r = get()\nassert r.ok\nassert r.body",
      new_string: "r = get()\nassert r.ok",
    },
    ctx,
  );
  assert.deepEqual(levels(f), ["ask"]);
  assert.match(f[0][1], /removes 1 assertion/);
});

test("adding a skip marker asks", () => {
  const f = check(
    "Edit",
    {
      file_path: "/repo/src/api.test.ts",
      old_string: "it('works', () => {",
      new_string: "it.skip('works', () => {",
    },
    ctx,
  );
  assert.match(f.map(([, r]) => r).join(), /skip/);
});

test("adding assertions to a test file passes", () => {
  assert.deepEqual(
    check(
      "Edit",
      {
        file_path: "/repo/tests/test_api.py",
        old_string: "assert a",
        new_string: "assert a\nassert b",
      },
      ctx,
    ),
    [],
  );
});

test("assertion changes outside test files pass", () => {
  assert.deepEqual(
    check(
      "Edit",
      { file_path: "/repo/src/app.py", old_string: "assert x", new_string: "" },
      ctx,
    ),
    [],
  );
});

test("lockfiles and dist output ask", () => {
  assert.deepEqual(
    levels(
      check(
        "Edit",
        {
          file_path: "/repo/package-lock.json",
          old_string: "a",
          new_string: "b",
        },
        ctx,
      ),
    ),
    ["ask"],
  );
  assert.deepEqual(
    levels(
      check("Write", { file_path: "/repo/dist/app.min.js", content: "x" }, ctx),
    ),
    ["ask"],
  );
});

test("files marked @generated ask", () => {
  const f = path.join(dir, "schema.ts");
  fs.writeFileSync(f, "// @generated by codegen\nexport type A = 1;\n");
  assert.deepEqual(
    levels(
      check("Edit", { file_path: f, old_string: "1", new_string: "2" }, ctx),
    ),
    ["ask"],
  );
});

test("a Write that drops most of a long file asks", () => {
  const f = path.join(dir, "big.py");
  fs.writeFileSync(f, "x = 1\n".repeat(200));
  assert.deepEqual(
    levels(check("Write", { file_path: f, content: "x = 1\n" }, ctx)),
    ["ask"],
  );
  assert.deepEqual(
    check("Write", { file_path: f, content: "x = 2\n".repeat(190) }, ctx),
    [],
  );
});

test("settings edits that enable fast mode are denied", () => {
  assert.deepEqual(
    levels(
      check(
        "Edit",
        {
          file_path: "/Users/u/.claude/settings.json",
          old_string: '"theme": "auto"',
          new_string: '"theme": "auto", "fastMode": true',
        },
        ctx,
      ),
    ),
    ["deny"],
  );
  assert.deepEqual(
    levels(
      check(
        "Write",
        {
          file_path: "/p/.claude/settings.local.json",
          content: JSON.stringify({
            env: { CLAUDE_CODE_DISABLE_FAST_MODE: "0" },
          }),
        },
        ctx,
      ),
    ),
    ["deny"],
  );
  assert.deepEqual(
    levels(
      check(
        "Write",
        {
          file_path: "/p/.claude/settings.json",
          content: JSON.stringify({ model: "sonnet" }),
        },
        ctx,
      ),
    ),
    ["deny"],
  );
});

test("other settings edits ask, and pass through when both guards are off", () => {
  const input = {
    file_path: "/p/.claude/settings.json",
    content: JSON.stringify({ theme: "dark" }),
  };
  assert.deepEqual(levels(check("Write", input, ctx)), ["ask"]);
  assert.deepEqual(
    check("Write", input, { ...ctx, editGuard: false, modelLock: false }),
    [],
  );
});

test("a settings.json outside .claude is ordinary", () => {
  assert.deepEqual(
    check(
      "Write",
      {
        file_path: "/repo/config/settings.json",
        content: '{"fastMode": true}',
      },
      ctx,
    ),
    [],
  );
});
