// Rules for the Edit/Write guard.
//
// check(toolName, toolInput, ctx) returns findings shaped [level, reason].

import fs from "node:fs";
import path from "node:path";
import { allowed } from "./_models.mjs";

/** @typedef {{allowedModels: string[], editGuard?: boolean, modelLock?: boolean}} Context */

export function check(toolName, toolInput, ctx) {
  const c = { editGuard: true, modelLock: true, ...ctx };
  const filePath = toolInput.file_path || toolInput.notebook_path || "";
  if (!filePath) return [];
  const posix = filePath.split(path.sep).join("/");
  const { before, after } = beforeAfter(toolName, toolInput, filePath);
  const out = [];
  if (isClaudeSettings(posix)) out.push(...settings(before, after, c));
  if (!c.editGuard) return out;
  if (TEST_PATH.test(posix)) out.push(...testWeakening(before, after));
  out.push(...generated(filePath, posix));
  if (toolName === "Write" && before !== null)
    out.push(...shrink(before, after));
  return out;
}

/** Old text (null when the file is new) and new text for each editing tool. */
function beforeAfter(toolName, input, filePath) {
  switch (toolName) {
    case "Edit":
      return { before: input.old_string ?? "", after: input.new_string ?? "" };
    case "MultiEdit": {
      const edits = Array.isArray(input.edits) ? input.edits : [];
      return {
        before: edits.map((e) => e.old_string ?? "").join("\n"),
        after: edits.map((e) => e.new_string ?? "").join("\n"),
      };
    }
    case "NotebookEdit":
      return { before: "", after: input.new_source ?? "" };
    default:
      return { before: readExisting(filePath), after: input.content ?? "" };
  }
}

function readExisting(filePath) {
  try {
    const stat = fs.statSync(filePath);
    return stat.isFile() && stat.size < 2_000_000
      ? fs.readFileSync(filePath, "utf8")
      : null;
  } catch {
    return null;
  }
}

function count(re, text) {
  return (
    text.match(new RegExp(re.source, `${re.flags.replace("g", "")}g`)) ?? []
  ).length;
}

// --- tests ------------------------------------------------------------------

const TEST_PATH =
  /(^|\/)(tests?|__tests__|spec|specs|testing)\/|(^|\/)test_[^/]+\.py$|_test\.(py|go|rs|exs?|dart)$|\.(test|spec)\.[cm]?[jt]sx?$|Tests?\.(swift|kt|java|cs)$|_spec\.rb$|Test\.php$/;
const ASSERT =
  /\bassert\w*\b|\bexpect\s*\(|XCTAssert\w*|#expect\b|#require\b|\bt\.(Error|Fatal|Fail)\w*\(|\brequire\.\w+\(|\.should\b|\bassert_(eq|ne)!|\bdebug_assert\w*!|\bAssert\.\w+\(|\bassertThat\(|\bverify\s*\(/;
const SKIP =
  /\b(it|test|describe|context)\.(skip|todo|only)\b|\b(xit|xdescribe|xtest|fit|fdescribe)\s*\(|@pytest\.mark\.(skip|xfail)|pytest\.skip\(|@unittest\.skip|\bself\.skipTest\(|#\[ignore\]|\bt\.Skip(Now|f)?\(|XCTSkip|\.disabled\(|@Disabled\b|@Ignore\b|\[Ignore\]|\[Fact\(Skip|\bskip:\s*true/;

function testWeakening(before, after) {
  const out = [];
  const removed = count(ASSERT, before ?? "") - count(ASSERT, after);
  if (removed > 0)
    out.push(["ask", `edit removes ${removed} assertion(s) from a test file`]);
  if (count(SKIP, after) > count(SKIP, before ?? ""))
    out.push([
      "ask",
      "edit adds a skip, xfail, todo, or focus marker to a test file",
    ]);
  return out;
}

// --- generated files --------------------------------------------------------

const GENERATED_PATH =
  /\.min\.(js|css)$|(^|\/)(dist|build|out|target|\.next|node_modules|vendor|Pods|DerivedData)\/|\.(pb|pb\.gw)\.go$|_pb2(_grpc)?\.pyi?$|\.g\.dart$|\.freezed\.dart$|\.generated\.\w+$|(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|Cargo\.lock|poetry\.lock|uv\.lock|Gemfile\.lock|composer\.lock|go\.sum|Package\.resolved|Podfile\.lock)$/;
const GENERATED_MARK = /@generated|DO NOT EDIT|auto-generated|autogenerated/i;

function generated(filePath, posix) {
  const name = path.basename(filePath);
  if (GENERATED_PATH.test(posix))
    return [
      [
        "ask",
        `${name} is generated, vendored, or a lockfile; the usual fix is to edit its source or rerun the generator`,
      ],
    ];
  let head = "";
  try {
    const fd = fs.openSync(filePath, "r");
    const buf = Buffer.alloc(1024);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    fs.closeSync(fd);
    head = buf
      .subarray(0, n)
      .toString("utf8")
      .split("\n")
      .slice(0, 5)
      .join("\n");
  } catch {
    head = "";
  }
  return GENERATED_MARK.test(head)
    ? [
        [
          "ask",
          `${name} is marked as generated; the usual fix is to edit its source or rerun the generator`,
        ],
      ]
    : [];
}

function shrink(before, after) {
  const oldLines = before.split("\n").length;
  const newLines = after.split("\n").length;
  return oldLines >= 80 && newLines <= oldLines * 0.4
    ? [["ask", `Write replaces a ${oldLines}-line file with ${newLines} lines`]]
    : [];
}

// --- Claude settings --------------------------------------------------------

const SETTINGS_NAME =
  /(^|\/)(settings(\.local)?\.json|managed-settings\.json)$/;
const FAST_DENY = "fast mode is turned off by dotclaude's model lock";

function isClaudeSettings(posix) {
  return (
    SETTINGS_NAME.test(posix) &&
    (posix.includes("/.claude/") ||
      posix.includes("managed-settings") ||
      posix.includes("ClaudeCode"))
  );
}

function loads(text) {
  try {
    const value = JSON.parse(text);
    return value && typeof value === "object" && !Array.isArray(value)
      ? value
      : null;
  } catch {
    return null;
  }
}

function settings(before, after, ctx) {
  const out = [];
  const parsed = loads(after);
  if (ctx.modelLock) {
    const fastOn = parsed
      ? parsed.fastMode === true
      : /"fastMode"\s*:\s*true/.test(after);
    const env = parsed?.env && typeof parsed.env === "object" ? parsed.env : {};
    const fastEnv =
      /"CLAUDE_CODE_DISABLE_FAST_MODE"\s*:\s*"0"/.test(after) ||
      (Object.hasOwn(env, "CLAUDE_CODE_DISABLE_FAST_MODE") &&
        String(env.CLAUDE_CODE_DISABLE_FAST_MODE) !== "1");
    if (fastOn || fastEnv) out.push(["deny", FAST_DENY]);
    for (const key of ["model", "advisorModel"]) {
      const value = parsed?.[key];
      if (typeof value === "string" && !allowed(value, ctx.allowedModels))
        out.push([
          "deny",
          `\`${key}: ${value}\` is outside the allowed models`,
        ]);
    }
  }
  if (
    /"disableAllHooks"\s*:\s*true/.test(after) &&
    !/"disableAllHooks"\s*:\s*true/.test(before ?? "")
  ) {
    out.push(["ask", "edit disables all Claude Code hooks"]);
  }
  if (ctx.editGuard && !out.length)
    out.push(["ask", "edit changes Claude Code settings"]);
  return out;
}
