import { expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { ASKS_TEST_REMOVAL, check } from "../../hooks/lib/_edit-rules.mjs";
import { nodeIo } from "../../hooks/lib/_io-node.mjs";

// A session with the dotclaude profile maps `sonnet` to Opus 5.5 through
// ANTHROPIC_DEFAULT_SONNET_MODEL, which would change what these aliases resolve to.
for (const family of ["OPUS", "SONNET", "HAIKU", "FABLE", "MYTHOS"])
  delete process.env[`ANTHROPIC_DEFAULT_${family}_MODEL`];

const ctx = {
  allowedModels: ["claude-opus-5-5", "claude-fable-5-1"],
  io: nodeIo(),
};
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dotclaude-edit-"));
const levels = (findings) => findings.map(([level]) => level);

test("removing an assertion from a test file asks", async () => {
  const f = await check(
    "Edit",
    {
      file_path: "/repo/tests/test_api.py",
      old_string: "r = get()\nassert r.ok\nassert r.body",
      new_string: "r = get()\nassert r.ok",
    },
    ctx,
  );
  expect(levels(f)).toStrictEqual(["ask"]);
  // The count of removed assertions.
  expect(f[0][1]).toMatch(/\b1\b/);
});

test("test-removal requests are recognized in the user's own words", () => {
  for (const said of [
    "rip it out: legacy.js, the USE_LEGACY_PRICING flag, its tests, all of it",
    "delete the flaky test",
    "these tests are obsolete, remove them",
  ])
    expect(ASKS_TEST_REMOVAL.test(said), said).toBeTruthy();
  for (const said of [
    "fix the failing test",
    "tests should still pass after",
    "remove the log line. Tests should pass",
  ])
    expect(!ASKS_TEST_REMOVAL.test(said), said).toBeTruthy();
});

test("adding a skip marker asks", async () => {
  const f = await check(
    "Edit",
    {
      file_path: "/repo/src/api.test.ts",
      old_string: "it('works', () => {",
      new_string: "it.skip('works', () => {",
    },
    ctx,
  );
  expect(levels(f)).toStrictEqual(["ask"]);
});

test("adding assertions to a test file passes", async () => {
  expect(
    await check(
      "Edit",
      {
        file_path: "/repo/tests/test_api.py",
        old_string: "assert a",
        new_string: "assert a\nassert b",
      },
      ctx,
    ),
  ).toStrictEqual([]);
});

test("assertion changes outside test files pass", async () => {
  expect(
    await check(
      "Edit",
      { file_path: "/repo/src/app.py", old_string: "assert x", new_string: "" },
      ctx,
    ),
  ).toStrictEqual([]);
});

test("lockfiles and dist output warn", async () => {
  expect(
    levels(
      await check(
        "Edit",
        {
          file_path: "/repo/package-lock.json",
          old_string: "a",
          new_string: "b",
        },
        ctx,
      ),
    ),
  ).toStrictEqual(["warn"]);
  expect(
    levels(
      await check(
        "Write",
        { file_path: "/repo/dist/app.min.js", content: "x" },
        ctx,
      ),
    ),
  ).toStrictEqual(["warn"]);
});

test("files marked @generated warn", async () => {
  const f = path.join(dir, "schema.ts");
  fs.writeFileSync(f, "// @generated by codegen\nexport type A = 1;\n");
  expect(
    levels(
      await check(
        "Edit",
        { file_path: f, old_string: "1", new_string: "2" },
        ctx,
      ),
    ),
  ).toStrictEqual(["warn"]);
});

test("a Write that drops most of a long file warns", async () => {
  const f = path.join(dir, "big.py");
  fs.writeFileSync(f, "x = 1\n".repeat(200));
  expect(
    levels(await check("Write", { file_path: f, content: "x = 1\n" }, ctx)),
  ).toStrictEqual(["warn"]);
  expect(
    await check("Write", { file_path: f, content: "x = 2\n".repeat(190) }, ctx),
  ).toStrictEqual([]);
});

test("skip markers in a new test file are not weakening", async () => {
  expect(
    await check(
      "Write",
      {
        file_path: path.join(dir, "tests", "test_new_platform.py"),
        content:
          '@unittest.skipUnless(shutil.which("openssl"), "needs openssl")\nclass T(unittest.TestCase):\n    def test_x(self):\n        self.assertTrue(True)\n',
      },
      ctx,
    ),
  ).toStrictEqual([]);
});

test("settings edits that enable fast mode are denied", async () => {
  expect(
    levels(
      await check(
        "Edit",
        {
          file_path: "/Users/u/.claude/settings.json",
          old_string: '"theme": "auto"',
          new_string: '"theme": "auto", "fastMode": true',
        },
        ctx,
      ),
    ),
  ).toStrictEqual(["deny"]);
  expect(
    levels(
      await check(
        "Write",
        {
          file_path: "/p/.claude/settings.local.json",
          content: JSON.stringify({
            env: { CLAUDE_CODE_DISABLE_FAST_MODE: "0" },
          }),
        },
        ctx,
      ),
    ),
  ).toStrictEqual(["deny"]);
  expect(
    levels(
      await check(
        "Write",
        {
          file_path: "/p/.claude/settings.json",
          content: JSON.stringify({ model: "sonnet" }),
        },
        ctx,
      ),
    ),
  ).toStrictEqual(["deny"]);
});

test("other settings edits ask, and pass through when both guards are off", async () => {
  const input = {
    file_path: "/p/.claude/settings.json",
    content: JSON.stringify({ theme: "dark" }),
  };
  expect(levels(await check("Write", input, ctx))).toStrictEqual(["ask"]);
  expect(
    await check("Write", input, { ...ctx, editGuard: false, modelLock: false }),
  ).toStrictEqual([]);
});

test("a settings.json outside .claude is ordinary", async () => {
  expect(
    await check(
      "Write",
      {
        file_path: "/repo/config/settings.json",
        content: '{"fastMode": true}',
      },
      ctx,
    ),
  ).toStrictEqual([]);
});

test("a Write whose frontmatter would not parse is denied", async () => {
  const f = await check(
    "Write",
    {
      file_path: path.join(dir, "SKILL.md"),
      content:
        "---\nname: x\ndescription: Does a thing: then another\n---\nBody\n",
    },
    ctx,
  );
  expect(levels(f)).toStrictEqual(["deny"]);
  expect(f[0][1]).toContain("`SKILL.md`");
});

test("quoted frontmatter values and colons without a space pass", async () => {
  for (const value of ['"Does a thing: then another"', "key:value"])
    expect(
      await check(
        "Write",
        {
          file_path: path.join(dir, "agent.md"),
          content: `---\nname: x\ndescription: ${value}\n---\n`,
        },
        ctx,
      ),
      value,
    ).toStrictEqual([]);
});

test("an Edit that breaks existing frontmatter is denied", async () => {
  const file = path.join(dir, "rule.md");
  fs.writeFileSync(file, '---\ndescription: "Old: fine"\n---\nBody\n');
  const f = await check(
    "Edit",
    {
      file_path: file,
      old_string: 'description: "Old: fine"',
      new_string: "description: New: broken",
    },
    ctx,
  );
  expect(levels(f)).toStrictEqual(["deny"]);
});

test("frontmatter-looking text outside Markdown files is not checked", async () => {
  expect(
    await check(
      "Write",
      {
        file_path: path.join(dir, "notes.txt"),
        content: "---\ndescription: a: b\n---\n",
      },
      ctx,
    ),
  ).toStrictEqual([]);
});
