name: ci
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.2
      - run: git config --global user.email ci@example.com && git config --global user.name ci
      - run: bunx @biomejs/biome@2.5.13 lint hooks tests skills
      - run: bun test ./tests/
